import { PlanAction } from "../types";
import { UserRole } from "../../types/auth";

export const ACTION_ROLE_REQUIREMENTS: Record<PlanAction, UserRole[]> = {
  create_task: ["admin"],
  update_task: ["admin"],
  delete_task: ["admin"],
  assign_task: ["admin"],
  change_status: ["admin"],
  change_priority: ["admin"],
  list_tasks: ["admin"],
  chat: ["admin"],
  create_customer: ["admin"],
  update_customer: ["admin"],
  delete_customer: ["admin"],
  view_customer: ["admin"],
  list_customers: ["admin"],
  create_sale: ["admin"],
  update_sale: ["admin"],
  delete_sale: ["admin"],
  view_sale: ["admin"],
  assign_sale: ["admin"],
  change_sale_status: ["admin"],
  list_sales: ["admin"],
  reprioritize_tasks: ["admin"],
  optimize_workload: ["admin"],
  schedule_plan: ["admin"],
  generate_report: ["admin"],
  analyze_productivity: ["admin"],
  detect_risk: ["admin"],
  automate_workflow: ["admin"],
  negotiate_deadline: ["admin"],
  strategic_planning: ["admin"],
  normal_chat: ["admin"],
};
